### ISSUE TITLE
SegWit

### ISSUE THREAD

**Issue by ruthtern** [matja/bitcoin-tool#26]
What is the nature of the work required to add SegWit addresses to bitcoin-tool? 
Is it a big job?

**Comment by k06a** [comment]
Same question

**Comment by hibiki-sensei** [comment]
Yes, a need it too.  Who can add this feature?

**Comment by streamofstars** [comment]
I would also appreciate a feature of generating Segwit and Bech32 Segwit addresses.

**Comment by streamofstars** [comment]
Recently, there was bech32 option added #36 to --input-format and --output-format so native SegWit addresses (P2WPKH, starting bc1) are now supported. This has not been documented yet, so I have just made a pull req. #39 with appropriate readme changes. I believe that P2SH-wrapped i.e. non-native SegWit addresses (starting 3) are still not supported.

**Comment by streamofstars** [comment]
@ruthtern since the bech32 address support is now added, can we assume this issue is resolved? If so, can you please close it?

**Comment by ruthtern** [comment]
Apologies for the delay. Now closing. Many thanks for this enhancement
