### ISSUE TITLE
wrong base58check to hex encoding

### ISSUE THREAD

**Issue by viktorheli** [matja/bitcoin-tool#32]
Hi. Bug: 
This command line:
bitcoin-tool --input-type address --input-format base58check --output-type address --output-format hex --input 15cLKZtKbqeSVxXWjhi5i4DjeftC8ky3bo

Give me following hex digit:
00328f307df6191bacf2bfdccfed12246fc19debd2

Going to Online Address Validator and Base58 Encoder/Decoder
http://lenschulwitz.com/base58
paste hex and see this: 
1hrXJp891VFJ8KLGRyszDoqLeJJV

Correct work, for example:
bx base58-decode 15cLKZtKbqeSVxXWjhi5i4DjeftC8ky3bo
00328f307df6191bacf2bfdccfed12246fc19debd24913a03a

http://lenschulwitz.com/base58 give:
15cLKZtKbqeSVxXWjhi5i4DjeftC8ky3bo

**Comment by matja** [comment]
For the first example, `00328f307df6191bacf2bfdccfed12246fc19debd2` is the prefix byte and 20-byte RMD160 hash (21 bytes in total), without the checksum (4 byte truncated SHA256 hash).
This patches the requested `--output-type address` as describe in the help page :

> address : 21 byte Bitcoin address (prefix + hash)

The site you mention expects a hex string with the checksum to be appended, which is the reason for the different address which was output (which is invalid).

I agree you have a valid point and bitcoin-tool should output this, so I've added a new output-type called `address-checksum` (I didn't want to change existing behavior).  You can pull the latest master branch to get this.

This will give you the output I believe you were expecting, when used like:
`./bitcoin-tool --input-type address --input-format base58check --output-type address-checksum --output-format hex --input 15cLKZtKbqeSVxXWjhi5i4DjeftC8ky3bo`

Output:
`00328f307df6191bacf2bfdccfed12246fc19debd24913a03a`

**Comment by viktorheli** [comment]
It works! Very BIG thanks!
